 <?php
 // module/Album/view/test/test/index.phtml:

 $title = 'My tests';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('test', array('action'=>'add'));?>">Add new test</a>
 </p>

 <table class="table">
 <tr>
     <th>Title</th>
     <th>Artist</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($tests as $test) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($test->title);?></td>
     <td><?php echo $this->escapeHtml($test->artist);?></td>
     <td>
         <a href="<?php echo $this->url('test',
             array('action'=>'edit', 'id' => $test->id));?>">Edit</a>
         <a href="<?php echo $this->url('test',
             array('action'=>'delete', 'id' => $test->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>
